MODULE CHEBYROOTS
  USE INTERFACE 
  
CONTAINS
  
  SUBROUTINE CHEBYCOMP(A,B,C)
    REAL(KIND=DP), INTENT(IN), DIMENSION(0:N) :: C
    REAL(KIND=DP), INTENT(IN) :: A, B

    REAL(KIND=DP), DIMENSION(N,N) :: M     !FROBENIUS-CHEBYSHEV COMPANION MATRIX
    
    INTEGER :: I1

    M = 0.0_DP
    
    DO I1 = 1,N-1
       M(I1,I1+1) = 0.5_DP
       M(I1+1,I1) = 0.5_DP
    END DO

    M(N,1:N) = (/ (-0.5_DP*C(I1-1)/C(N), I1=1,N) /)

    M(1,2) = 1.0_DP
    M(N,N-1) = M(N,N-1) + 0.5_DP

    CALL EIGEN(A,B,M)
    
    RETURN
  END SUBROUTINE CHEBYCOMP

  SUBROUTINE EIGEN(A,B,M)
    REAL(KIND=DP), DIMENSION(N,N) :: M
    REAL(KIND=DP), INTENT(IN) :: A, B

    REAL(KIND=DP), DIMENSION(N) :: ALLROOTS
    
    CHARACTER :: JOBVL = 'N', JOBVE = 'N', INFO
    REAL(KIND=DP), DIMENSION(N) :: WR, WI
    REAL(KIND=DP), DIMENSION(1) :: VR, VL
    INTEGER, PARAMETER :: LDVL = 1, LDVR = 1, LWORK = 5*N
    REAL(KIND=DP), DIMENSION(LWORK) :: WORK

    INTEGER :: I1,I2
    
    CALL DGEEV(JOBVL, JOBVE, N, M, N, WR, WI, VL, LDVL, VR, LDVR, WORK, LWORK, INFO)

    ALLROOTS = 0.0_DP
    PRINT *,
    DO I1 = 1,N
       IF(ABS(WI(I1)) .LT. 1.D-16 .AND. ABS(WR(I1)) .LE. 1.0_DP) THEN
          ALLROOTS(I1) = WR(I1)
          PRINT *, 0.5_DP*(B-A)*ALLROOTS(I1) + 0.5_DP*(B+A)
       END IF
    END DO
    
  END SUBROUTINE EIGEN
END MODULE CHEBYROOTS
