!!$ THINK FLOW:
!!$ - TRANSFORM F(X) INTO A "CHEBYSHEV'S VECTOR"
!!$ - CONSTRUCT A "COMPANION MATRIX"
!!$ - SOLVE EIGENVALUES OF THIS MATRIX
!!$ - REFINE(?)

PROGRAM CPR
  USE CHEBYINTER
  IMPLICIT NONE

!  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15,307)
  
  REAL(KIND=8) :: A = -3.15_DP, B = 3.15_DP
  
  REAL(KIND=8), DIMENSION(0:N) :: C
  
  INTEGER :: I1

  CALL INTERPOLATE(A,B,C)
!  CALL FIND_EIGEN()

CONTAINS

  
END PROGRAM CPR
