!!$ THINK FLOW:
!!$ - TRANSFORM F(X) INTO A "CHEBYSHEV'S VECTOR"
!!$ - CONSTRUCT A "COMPANION MATRIX"
!!$ - SOLVE EIGENVALUES OF THIS MATRIX
!!$ - REFINE(?)

PROGRAM CPR
  USE INTERFACE
  USE INTERPOLATION
  USE COMPANION
  IMPLICIT NONE

  INTEGER :: I1

     CALL CHEBY_INTERPOLATE(COEF, L, R)
     CALL FIND_EIGEN()
  
END PROGRAM CPR
