!!$ CALCULATING CHEBYSHEV INTERPOLATION AS IN APPENDIX B2 OF JOHN P. BOYD

MODULE INTERPOLATION 
  USE INTERFACE
  IMPLICIT NONE
      
  REAL(KIND=DP), DIMENSION(0:N) :: F        !GRID POINTS FOR FUNCTION F
  REAL(KIND=DP), DIMENSION(0:N) :: X        !INTERPOLATION POINTS (LOBATTO GRID)
  REAL(KIND=DP), DIMENSION(0:N,0:N) :: J    !INTERPOLATION MATRIX
  
CONTAINS
  
  SUBROUTINE CHEBY_INTERPOLATE(C,A,B)
    USE OGPF
    REAL(KIND=DP), INTENT(IN) :: A,B
    
    REAL(KIND=DP), DIMENSION(0:N) :: C, XI, EVAL
    INTEGER :: I1,I2,PJ,PK
    REAL(KIND=DP) :: BMA,BPA
    
    TYPE(GPF) :: GPLOT

!!$ STEP 1 CONSTRUCT THE LOBBATO GRID AND F(X)

    X = 0.0_DP
    F = 0.0_DP

    BMA = (B-A)/2.0_DP
    BPA = (B+A)/2.0_DP
    
    X(0:N) = (/ (COS(PI * DBLE(I1) / DBLE(N) * BMA + BPA), I1 = 0,N) /)
    F(0:N) = (/ (G(X(I1)), I1 = 0,N) /)

!!$ STEP 2 CONSTRUCT THE INTERPOLATION MATRIX AND OBTAIN THE COEFFICIENTS
    J = 0.0_DP
    C = 0.0_DP
    
    DO I1=0,N
       PJ = 1
       IF(I1 .EQ. 0 .OR. I1 .EQ. N) PJ = 2
       DO I2=0,N
          PK = 1
          IF(I2 .EQ. 0 .OR. I2 .EQ. N) PK = 2
          
          J(I1,I2) = 2.0_DP * COS(PI * DBLE(I1) * DBLE(I2) / DBLE(N)) / DBLE(PJ) / DBLE(PK) / DBLE(N)

          C(I1) = C(I1) + J(I1,I2) * F(I2)
          
       END DO
    END DO
    
    PRINT *, 'PRINTING COEFFICIENT OF CHEBYSHEV INTERPOLATION'
    DO I1=0,N
       PRINT *, C(I1)
    END DO
    
!!$ STEP 3 SUM THE CHEBYSHEV APPROXIMATION    

    EVAL = 0.0_DP

    DO I1=0,N
       DO I2=0,N
          EVAL(I1) = EVAL(I1) + C(I2) * COS( DBLE(I2) * ACOS( (2.0_DP * X(I1) - B - A)/(B - A)))
       END DO
    END DO
    
    CALL GPLOT%PLOT(X, EVAL)

    RETURN
  END SUBROUTINE CHEBY_INTERPOLATE

  FUNCTION G(X) RESULT(J)
    REAL(KIND=DP) :: J
    REAL(KIND=DP), INTENT(IN) :: X
    
    J = COS(COSH(2.0_DP*X))
    
    RETURN

  END FUNCTION G
  
END MODULE INTERPOLATION
