MODULE interface

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15,307)
  REAL(KIND=DP) :: PI = ACOS(-1.0_DP)

  REAL(KIND=DP) :: L = -1.0_DP, R = 1.0_DP
  INTEGER, PARAMETER :: N = 8
  REAL(KIND=DP), DIMENSION(0:N) :: COEF
END MODULE interface
